### ISSUE TITLE
BBVA

### ISSUE THREAD

**Issue by siristi** [Castrogiovanni20/api-dolar-argentina#1]
buenas tardes, necesitaria obtener los valores del oficial BBVA, se que es la casa 336.
es esto posible ?

**Comment by Castrogiovanni20** [comment]
Buenas, es posible, dame unos dias y agrego un endpoint que devuelva los valores del BBVA. Saludos

**Comment by siristi** [comment]
genial! muchas gracias !

**Comment by Castrogiovanni20** [comment]
@siristi agregué un endpoint para obtener los valores del BBVA. 
Podes consultarlo haciendo un GET a https://api-dolar-argentina.herokuapp.com/api/bbva

Saludos

**Comment by siristi** [comment]
Me salvaste la vida. Gracias!
