### ISSUE TITLE
Podrías agregar un endpoint que de toda la info de los distintos tipos de dolar?

### ISSUE THREAD

**Issue by Ambro17** [Castrogiovanni20/api-dolar-argentina#10]
Estoy armando un script que compara la evolución del oficial vs el resto y me sería útil que con una sola llamada vengan los datos de todas las cotizaciones del dolar.

Lo ves viable? 

Muchas gracias de antemano por desarrollar esto que está muy bueno

**Comment by Castrogiovanni20** [comment]
Hola, como andas?
Dale, voy a tratar de agregarlo en la semana!

Saludos

**Comment by Ambro17** [comment]
Muchas gracias!!!

**Comment by Castrogiovanni20** [comment]
Endpoint agregado: https://api-dolar-argentina.herokuapp.com/api/all

Espero que te sirva

Saludos!

**Comment by Ambro17** [comment]
Gracias capo
