### ISSUE TITLE
Dolar Divisa: agregar Mayorista Bancos?

### ISSUE THREAD

**Issue by korrakeala** [Castrogiovanni20/api-dolar-argentina#11]
Hola, cómo va?
Estoy desarrollando un servicio que consume tu API (chapeau y gracias btw!) y estaría necesitando levantar el Mayorista Bancos (casa44). Será posible agregarlo? Gracias!

**Comment by Castrogiovanni20** [comment]
Buen dia, dale no hay problema, mañana lo agrego. Saludos!

**Comment by korrakeala** [comment]
genial! mil gracias :D

**Comment by Castrogiovanni20** [comment]
Endpoint agregado: https://api-dolar-argentina.herokuapp.com/api/mayorista

Saludos!
