### ISSUE TITLE
Application error (503)

### ISSUE THREAD

**Issue by adopeder** [Castrogiovanni20/api-dolar-argentina#15]
Está dando 503 en los 2 dominios. Podrías revisarlo, por favor?
![image](https://user-images.githubusercontent.com/84116513/118078518-c1042600-b38c-11eb-8bce-25d21cb1fa1b.png)

**Comment by Castrogiovanni20** [comment]
Resuelto

**Comment by adopeder** [comment]
Millón gracias.
