### ISSUE TITLE
Application error

### ISSUE THREAD

**Issue by siristi** [Castrogiovanni20/api-dolar-argentina#2]
![Screenshot from 2020-08-27 16-10-17](https://user-images.githubusercontent.com/45299546/91484625-ee04bd00-e87f-11ea-9f8f-eb9fa6504575.png)

**Comment by Castrogiovanni20** [comment]
Hi, thanks for letting me know. I will fix it asap

**Comment by Castrogiovanni20** [comment]
@siristi Now, app is up
