### ISSUE TITLE
Como se usa?

### ISSUE THREAD

**Issue by Ysma95** [Castrogiovanni20/api-dolar-argentina#20]
hola! alguien me puede decir como se usa esta API... estoy usando PHP

**Comment by santstor** [comment]
Tendrias que hacer un GET a la URL (https://api-dolar-argentina.herokuapp.com/) + endpoint (lo sacas del listado del readme.md). Un ejemplo:

`GET https://api-dolar-argentina.herokuapp.com/api/dolarblue`

Response:
```
{
        "fecha": "2021/11/02 16:29:32",
        "compra": "194.00",
        "venta": "197.00"
}
```
