### ISSUE TITLE
API caída, Application Error

### ISSUE THREAD

**Issue by bernardomichel** [Castrogiovanni20/api-dolar-argentina#25]
Buenos días! Estoy usando su api para integrarlo con un tablero en excel y esta mañana me encontré con que el servidor de heroku no está funcionando!

Al hacer un request HTTP, me devuelve ApplicationError:
```
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
```

Simplemente era para reportarlo. Si tienen un canal de reportes de este estilo, lo mando por ahí! Saludos y muchas gracias por semejante api

**Comment by Castrogiovanni20** [comment]
Buen día, solucionado, gracias por reportarlo

**Comment by creativoma** [comment]
Buenas! Aprovecho el hilo para agradecer tambien por la API! 

Consultar, porque la de Banco Nación no estaría tomando los decimales
https://api-dolar-argentina.herokuapp.com/api/nacion
Figura 109.00

Y aquí figura 109.25
https://www.bna.com.ar/Personas

Saludos!

**Comment by Castrogiovanni20** [comment]
Buenas! La info es obtenida del sitio https://www.dolarsi.com/
