### ISSUE TITLE
Dolar promedio

### ISSUE THREAD

**Issue by guidospadavecchia** [Castrogiovanni20/api-dolar-argentina#3]
Hola!

Estoy codeando un bot de Discord que utiliza tu API. Ante todo gracias por exponerla, me es de mucha utilidad.
La duda que tengo es que está devolviendo exactamente el "Dolar promedio"? Es la cotización promedio entre todos los bancos? Perdón si estoy preguntando alguna obviedad, lo googlee y no encontré nada.

Gracias

**Comment by Castrogiovanni20** [comment]
Hola,

Que bueno! 
Por lo que vi, creería que es el valor promedio del dolar oficial.
Esta es la pagina de donde obtiene los valores la API: https://www.dolarhoy.com/
Cualquier otra duda o solicitud de endpoint avisame

Abrazo

**Comment by guidospadavecchia** [comment]
Si, me imaginé que era el promedio de los bancos. Y el endpoint de Dolar Oficial supongo que será el valor del Banco Nación.
