### ISSUE TITLE
Valores Api Nacion

### ISSUE THREAD

**Issue by Clausuppo** [Castrogiovanni20/api-dolar-argentina#33]
Buenos dias! estoy verificando que la llamada a la API de Banco Nación no esta trayendo los valores que estan publicados en la pagina BNA.com.ar.
La llamada me devuelve:
{
    "fecha": "2022/06/28 15:09:43",
    "compra": "122.50",
    "venta": "128.50"
}
cuando en la pagina figura:
28/6/2022 | Compra | Venta
-- | -- | --
Dolar U.S.A | 123,7500 | 129,7500
Euro | 127,7500 | 134,7500
Real * | 2170,0000 | 2570,0000

Puede ser que este tomando mal los valores? me pasa lo mismo que con el Euro.

Gracias!

**Comment by Castrogiovanni20** [comment]
Hola, los valores son extraidos del sitio DolarSi, por favor comparalo contra lo que muestra DolarSi
