### ISSUE TITLE
Uncaught SyntaxError: unexpected token: ':'

### ISSUE THREAD

**Issue by XabierGallardo** [Castrogiovanni20/api-dolar-argentina#5]
Hola! Muchas gracias por tu API, es de mucha utilidad.

Tuve un par de problemas para conseguir los datos de la API, en primer lugar hasta que no especifiqué en el header **dataType: "jsonp"** me tiraba el siguiente error:

_Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api-dolar-argentina.herokuapp.com/api/dolaroficial?callback=?. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing)._

Ahora que especifiqué ese dataType el problema que me tira es:

_Uncaught SyntaxError: unexpected token: ':'_

Sin embargo el JSON puedo verlo a través del navegador. Seguramente el problema sea alguna especificación que no tengo en el header, pero no consigo encontrar la solución. Te dejo acá la petición por si te sirve de algo, gracias de nuevo!

```sh
$.ajax({
		url: "https://api-dolar-argentina.herokuapp.com/api/dolaroficial",
		type: "GET",
		dataType: "jsonp",
		success: function(data) {
			console.table(data);
		}
	});
```

**Comment by Castrogiovanni20** [comment]
Hola!
Muchas gracias por tu comentario. 
Fijate de probar ahora, habilite CORS, por lo que deberías cambiar **dataType: "json"**.
Y otra cosa que agregaría en el header **contentType: 'application/json'**

Cualquier cosa avisame

Saludos

**Comment by XabierGallardo** [comment]
Hola, acabo de probar y el siguiente código me devuelve este resultado:
```sh
$.ajax({
		url: "https://api-dolar-argentina.herokuapp.com/api/dolaroficial",
		type: "GET",
		dataType: "json",
		contentType: "application/json",

		success: function(data) {
			console.table(data);
}
});
```
**Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api-dolar-argentina.herokuapp.com/api/dolaroficial. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).**

**Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api-dolar-argentina.herokuapp.com/api/dolaroficial. (Reason: CORS request did not succeed).**

Cambiando el **dataType: "jsonp"** me devuelve un warning y un error:

**The script from “https://api-dolar-argentina.herokuapp.com/api/dolaroficial?callback=jQuery341011532663752181105_1603892592023&_=1603892592024” was loaded even though its MIME type (“application/json”) is not a valid JavaScript MIME type.**

**Uncaught SyntaxError: unexpected token: ':'**

Sorteado el problema del CORS con jsonp, y de acuerdo a este post, parecería que el problema es este:
https://stackoverflow.com/questions/3143698/uncaught-syntaxerror-unexpected-token

_Just an FYI for people who might have the same problem -- I just had to make my server send back the JSON as application/json and the default jQuery handler worked fine._

Probé a parsear el resultado con JSON.parse(data) y tampoco resulta. La verdad no tengo idea porque con el navegador puedo visualizar el JSON sin problema.

Gracias por responder! 

Saludos
