### ISSUE TITLE
muy buena, se podrian agregar casas de cambio?

### ISSUE THREAD

**Issue by kevindevm** [Castrogiovanni20/api-dolar-argentina#7]
como puse en el titulo estaría bueno si podrías agrega casas de cambio como las que aparece acá https://www.infodolar.com/cotizacion-dolar.aspx

**Comment by Castrogiovanni20** [comment]
Buenas, si dale, dame unos dias y las agrego. Abrazo

**Comment by Castrogiovanni20** [comment]
Agregue algunas casas de cambio principales de CABA, La Plata, Mar del Plata, Rosario, Mendoza y Tucuman. Espero te sea útil. Saludos
